# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6f34c41b983ebc292cb29f76beb742cead4684ecba122866737693beddf1110d6c9f034ce7c8975cd8e75ceff741637efb0062fa140063b09f3851af37af9dc

test:
  secret_key_base: 1dd6649f924e599f39f163bae1b32d73a99ee67f219bcb47693e3f94d87534cb17dd6e714e21a50780cd82eb5ce96a3b2d46bbb0b9a1bef5dea62cf3176eddf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
